version: 2

# golangci-lint configuration
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - internal/repository/mocks

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects unused assignments
    - staticcheck   # Static analysis
    - unused        # Checks for unused code
    - misspell      # Finds commonly misspelled words
    - revive        # Fast, configurable, extensible linter

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Printf
      - fmt.Println

issues:
  exclude-rules:
    # Exclude errcheck for test files
    - path: _test\.go
      linters:
        - errcheck
    # Exclude errcheck for defer statements in main
    - text: "Error return value of .*(Close|Flush)" 
      linters:
        - errcheck