with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
packages:
  github.com/R4yL-dev/pkmc/internal/repository:
    interfaces:
      UnitOfWork:
      ItemRepository:
      ExtensionRepository:
      LanguageRepository:
      ItemTypeRepository: