// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/R4yL-dev/pkmc/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockItemRepository is an autogenerated mock type for the ItemRepository type
type MockItemRepository struct {
	mock.Mock
}

type MockItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemRepository) EXPECT() *MockItemRepository_Expecter {
	return &MockItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: item
func (_m *MockItemRepository) Create(item *models.Item) error {
	ret := _m.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Item) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - item *models.Item
func (_e *MockItemRepository_Expecter) Create(item interface{}) *MockItemRepository_Create_Call {
	return &MockItemRepository_Create_Call{Call: _e.mock.On("Create", item)}
}

func (_c *MockItemRepository_Create_Call) Run(run func(item *models.Item)) *MockItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.Item))
	})
	return _c
}

func (_c *MockItemRepository_Create_Call) Return(_a0 error) *MockItemRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockItemRepository_Create_Call) RunAndReturn(run func(*models.Item) error) *MockItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockItemRepository) FindByID(id uint) (*models.Item, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.Item, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.Item); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockItemRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id uint
func (_e *MockItemRepository_Expecter) FindByID(id interface{}) *MockItemRepository_FindByID_Call {
	return &MockItemRepository_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockItemRepository_FindByID_Call) Run(run func(id uint)) *MockItemRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockItemRepository_FindByID_Call) Return(_a0 *models.Item, _a1 error) *MockItemRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemRepository_FindByID_Call) RunAndReturn(run func(uint) (*models.Item, error)) *MockItemRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemRepository creates a new instance of MockItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemRepository {
	mock := &MockItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
