// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/R4yL-dev/pkmc/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: ctx, fn
func (_m *MockUnitOfWork) Do(ctx context.Context, fn func(repository.UnitOfWork) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(repository.UnitOfWork) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnitOfWork_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockUnitOfWork_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(repository.UnitOfWork) error
func (_e *MockUnitOfWork_Expecter) Do(ctx interface{}, fn interface{}) *MockUnitOfWork_Do_Call {
	return &MockUnitOfWork_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *MockUnitOfWork_Do_Call) Run(run func(ctx context.Context, fn func(repository.UnitOfWork) error)) *MockUnitOfWork_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(repository.UnitOfWork) error))
	})
	return _c
}

func (_c *MockUnitOfWork_Do_Call) Return(_a0 error) *MockUnitOfWork_Do_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Do_Call) RunAndReturn(run func(context.Context, func(repository.UnitOfWork) error) error) *MockUnitOfWork_Do_Call {
	_c.Call.Return(run)
	return _c
}

// Extensions provides a mock function with no fields
func (_m *MockUnitOfWork) Extensions() repository.ExtensionRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Extensions")
	}

	var r0 repository.ExtensionRepository
	if rf, ok := ret.Get(0).(func() repository.ExtensionRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ExtensionRepository)
		}
	}

	return r0
}

// MockUnitOfWork_Extensions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extensions'
type MockUnitOfWork_Extensions_Call struct {
	*mock.Call
}

// Extensions is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) Extensions() *MockUnitOfWork_Extensions_Call {
	return &MockUnitOfWork_Extensions_Call{Call: _e.mock.On("Extensions")}
}

func (_c *MockUnitOfWork_Extensions_Call) Run(run func()) *MockUnitOfWork_Extensions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_Extensions_Call) Return(_a0 repository.ExtensionRepository) *MockUnitOfWork_Extensions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Extensions_Call) RunAndReturn(run func() repository.ExtensionRepository) *MockUnitOfWork_Extensions_Call {
	_c.Call.Return(run)
	return _c
}

// ItemTypes provides a mock function with no fields
func (_m *MockUnitOfWork) ItemTypes() repository.ItemTypeRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ItemTypes")
	}

	var r0 repository.ItemTypeRepository
	if rf, ok := ret.Get(0).(func() repository.ItemTypeRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ItemTypeRepository)
		}
	}

	return r0
}

// MockUnitOfWork_ItemTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ItemTypes'
type MockUnitOfWork_ItemTypes_Call struct {
	*mock.Call
}

// ItemTypes is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) ItemTypes() *MockUnitOfWork_ItemTypes_Call {
	return &MockUnitOfWork_ItemTypes_Call{Call: _e.mock.On("ItemTypes")}
}

func (_c *MockUnitOfWork_ItemTypes_Call) Run(run func()) *MockUnitOfWork_ItemTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_ItemTypes_Call) Return(_a0 repository.ItemTypeRepository) *MockUnitOfWork_ItemTypes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_ItemTypes_Call) RunAndReturn(run func() repository.ItemTypeRepository) *MockUnitOfWork_ItemTypes_Call {
	_c.Call.Return(run)
	return _c
}

// Items provides a mock function with no fields
func (_m *MockUnitOfWork) Items() repository.ItemRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Items")
	}

	var r0 repository.ItemRepository
	if rf, ok := ret.Get(0).(func() repository.ItemRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.ItemRepository)
		}
	}

	return r0
}

// MockUnitOfWork_Items_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Items'
type MockUnitOfWork_Items_Call struct {
	*mock.Call
}

// Items is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) Items() *MockUnitOfWork_Items_Call {
	return &MockUnitOfWork_Items_Call{Call: _e.mock.On("Items")}
}

func (_c *MockUnitOfWork_Items_Call) Run(run func()) *MockUnitOfWork_Items_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_Items_Call) Return(_a0 repository.ItemRepository) *MockUnitOfWork_Items_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Items_Call) RunAndReturn(run func() repository.ItemRepository) *MockUnitOfWork_Items_Call {
	_c.Call.Return(run)
	return _c
}

// Languages provides a mock function with no fields
func (_m *MockUnitOfWork) Languages() repository.LanguageRepository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Languages")
	}

	var r0 repository.LanguageRepository
	if rf, ok := ret.Get(0).(func() repository.LanguageRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.LanguageRepository)
		}
	}

	return r0
}

// MockUnitOfWork_Languages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Languages'
type MockUnitOfWork_Languages_Call struct {
	*mock.Call
}

// Languages is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) Languages() *MockUnitOfWork_Languages_Call {
	return &MockUnitOfWork_Languages_Call{Call: _e.mock.On("Languages")}
}

func (_c *MockUnitOfWork_Languages_Call) Run(run func()) *MockUnitOfWork_Languages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_Languages_Call) Return(_a0 repository.LanguageRepository) *MockUnitOfWork_Languages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Languages_Call) RunAndReturn(run func() repository.LanguageRepository) *MockUnitOfWork_Languages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
