// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/R4yL-dev/pkmc/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockLanguageRepository is an autogenerated mock type for the LanguageRepository type
type MockLanguageRepository struct {
	mock.Mock
}

type MockLanguageRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLanguageRepository) EXPECT() *MockLanguageRepository_Expecter {
	return &MockLanguageRepository_Expecter{mock: &_m.Mock}
}

// FindByCode provides a mock function with given fields: ctx, code
func (_m *MockLanguageRepository) FindByCode(ctx context.Context, code string) (*models.Language, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *models.Language
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Language, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Language); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Language)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLanguageRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockLanguageRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockLanguageRepository_Expecter) FindByCode(ctx interface{}, code interface{}) *MockLanguageRepository_FindByCode_Call {
	return &MockLanguageRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *MockLanguageRepository_FindByCode_Call) Run(run func(ctx context.Context, code string)) *MockLanguageRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLanguageRepository_FindByCode_Call) Return(_a0 *models.Language, _a1 error) *MockLanguageRepository_FindByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLanguageRepository_FindByCode_Call) RunAndReturn(run func(context.Context, string) (*models.Language, error)) *MockLanguageRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLanguageRepository creates a new instance of MockLanguageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLanguageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLanguageRepository {
	mock := &MockLanguageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
