// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/R4yL-dev/pkmc/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockExtensionRepository is an autogenerated mock type for the ExtensionRepository type
type MockExtensionRepository struct {
	mock.Mock
}

type MockExtensionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExtensionRepository) EXPECT() *MockExtensionRepository_Expecter {
	return &MockExtensionRepository_Expecter{mock: &_m.Mock}
}

// FindByCode provides a mock function with given fields: code
func (_m *MockExtensionRepository) FindByCode(code string) (*models.Extension, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *models.Extension
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Extension, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Extension); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Extension)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExtensionRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type MockExtensionRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - code string
func (_e *MockExtensionRepository_Expecter) FindByCode(code interface{}) *MockExtensionRepository_FindByCode_Call {
	return &MockExtensionRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", code)}
}

func (_c *MockExtensionRepository_FindByCode_Call) Run(run func(code string)) *MockExtensionRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockExtensionRepository_FindByCode_Call) Return(_a0 *models.Extension, _a1 error) *MockExtensionRepository_FindByCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExtensionRepository_FindByCode_Call) RunAndReturn(run func(string) (*models.Extension, error)) *MockExtensionRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExtensionRepository creates a new instance of MockExtensionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtensionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtensionRepository {
	mock := &MockExtensionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
