// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/R4yL-dev/pkmc/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockItemTypeRepository is an autogenerated mock type for the ItemTypeRepository type
type MockItemTypeRepository struct {
	mock.Mock
}

type MockItemTypeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemTypeRepository) EXPECT() *MockItemTypeRepository_Expecter {
	return &MockItemTypeRepository_Expecter{mock: &_m.Mock}
}

// FindByName provides a mock function with given fields: name
func (_m *MockItemTypeRepository) FindByName(name string) (*models.ItemType, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *models.ItemType
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.ItemType, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *models.ItemType); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ItemType)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockItemTypeRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockItemTypeRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - name string
func (_e *MockItemTypeRepository_Expecter) FindByName(name interface{}) *MockItemTypeRepository_FindByName_Call {
	return &MockItemTypeRepository_FindByName_Call{Call: _e.mock.On("FindByName", name)}
}

func (_c *MockItemTypeRepository_FindByName_Call) Run(run func(name string)) *MockItemTypeRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockItemTypeRepository_FindByName_Call) Return(_a0 *models.ItemType, _a1 error) *MockItemTypeRepository_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockItemTypeRepository_FindByName_Call) RunAndReturn(run func(string) (*models.ItemType, error)) *MockItemTypeRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItemTypeRepository creates a new instance of MockItemTypeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemTypeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemTypeRepository {
	mock := &MockItemTypeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
